services:
  jobify-auth:
    build:
      context: .
      dockerfile: ./jobify-auth/Dockerfile
      args:
        - SERVICE_NAME=jobify-auth
    image: jobify-auth:latest
    container_name: jobify-auth
    hostname: auth
    networks:
      - jobify-network
    ports:
      - "8080"
    restart: "unless-stopped"
  jobify-jobs:
    build:
      context: .
      dockerfile: ./jobify-jobs/Dockerfile
      args:
        - SERVICE_NAME=jobify-jobs
    image: jobify-jobs:latest
    container_name: jobify-jobs
    hostname: jobs
    networks:
      - jobify-network
    ports:
      - "8081"
    restart: "unless-stopped"
  jobify-apidocs:
    build:
      context: .
      dockerfile: ./jobify-apidocs/Dockerfile
      args:
        - SERVICE_NAME=jobify-apidocs
    image: jobify-apidocs:latest
    container_name: jobify-apidocs
    hostname: apidocs
    networks:
      - jobify-network
    ports:
      - "3000"
    environment:
      - PORT=3000
      - SERVICES=auth:8080,jobs:8081
      - NODE_ENV=production
    depends_on:
      - jobify-auth
      - jobify-jobs
    restart: "unless-stopped"

networks:
  jobify-network:
    driver: bridge
    name: jobify-network
